$arr:/pree/admin/blog/retrieve<span style="color:red;">file:C:\wamp\www\pree\library\zx\controller\route.phpline:39class:Zx\Controller\Routemethod:Zx\Controller\Route::analyze_url</span><br /><br />$arr:/pree/admin/blogcategory/retrieve<span style="color:red;">file:C:\wamp\www\pree\library\zx\controller\route.phpline:39class:Zx\Controller\Routemethod:Zx\Controller\Route::analyze_url</span><br /><br />$upload_dir:upload\\<span style="color:red;">file:C:\wamp\www\pree\js\ckeditor\j_ckfileuploader.phpline:13class:method:</span><br /><br />_FILES:Array
(
    [upload] => Array
        (
            [name] => cystic_fib_logo.png
            [type] => image/png
            [tmp_name] => C:\wamp\tmp\php1DC4.tmp
            [error] => 0
            [size] => 1591
        )

)
<span style="color:red;">file:C:\wamp\www\pree\js\ckeditor\j_ckedit.class.phpline:135class:CKEDITORmethod:CKEDITOR::ckFile</span><br /><br />php_upload_file:C:\wamp\www\pree\upload\\5074f1ad0b8c0cystic_fib_logo.png<span style="color:red;">file:C:\wamp\www\pree\js\ckeditor\j_ckedit.class.phpline:136class:CKEDITORmethod:CKEDITOR::ckFile</span><br /><br />url:http://localhosthttp://localhost/pree/upload\\5074f1ad0b8c0cystic_fib_logo.png<span style="color:red;">file:C:\wamp\www\pree\js\ckeditor\j_ckedit.class.phpline:147class:CKEDITORmethod:CKEDITOR::ckFile</span><br /><br />$upload_dir:upload/<span style="color:red;">file:C:\wamp\www\pree\js\ckeditor\j_ckfileuploader.phpline:13class:method:</span><br /><br />_FILES:Array
(
    [upload] => Array
        (
            [name] => cystic_fib_logo.png
            [type] => image/png
            [tmp_name] => C:\wamp\tmp\php5A38.tmp
            [error] => 0
            [size] => 1591
        )

)
<span style="color:red;">file:C:\wamp\www\pree\js\ckeditor\j_ckedit.class.phpline:135class:CKEDITORmethod:CKEDITOR::ckFile</span><br /><br />php_upload_file:C:\wamp\www\pree\upload/5074f23f847cbcystic_fib_logo.png<span style="color:red;">file:C:\wamp\www\pree\js\ckeditor\j_ckedit.class.phpline:136class:CKEDITORmethod:CKEDITOR::ckFile</span><br /><br />url:http://localhosthttp://localhost/pree/upload/5074f23f847cbcystic_fib_logo.png<span style="color:red;">file:C:\wamp\www\pree\js\ckeditor\j_ckedit.class.phpline:147class:CKEDITORmethod:CKEDITOR::ckFile</span><br /><br />$upload_dir:upload/<span style="color:red;">file:C:\wamp\www\pree\js\ckeditor\j_ckfileuploader.phpline:13class:method:</span><br /><br />_FILES:Array
(
    [upload] => Array
        (
            [name] => cystic_fib_logo.png
            [type] => image/png
            [tmp_name] => C:\wamp\tmp\php98DE.tmp
            [error] => 0
            [size] => 1591
        )

)
<span style="color:red;">file:C:\wamp\www\pree\js\ckeditor\j_ckedit.class.phpline:135class:CKEDITORmethod:CKEDITOR::ckFile</span><br /><br />php_upload_file:C:\wamp\www\pree\upload/5074f24f91f83cystic_fib_logo.png<span style="color:red;">file:C:\wamp\www\pree\js\ckeditor\j_ckedit.class.phpline:136class:CKEDITORmethod:CKEDITOR::ckFile</span><br /><br />url:http://localhosthttp://localhost/pree/upload/5074f24f91f83cystic_fib_logo.png<span style="color:red;">file:C:\wamp\www\pree\js\ckeditor\j_ckedit.class.phpline:147class:CKEDITORmethod:CKEDITOR::ckFile</span><br /><br />id:11<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:68class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='a1',`title_en`='a1',`content`='<p>
	<a href="http://localhost/pree/upload/5074f2a9187aecystic_fib_logo.png"><img alt="" src="http://localhost/pree/upload/5074f2e639a08cystic_fib_logo.png" style="width: 60px; height: 60px; " /></a></p>',`keyword`='',`keyword_en`='',`url`='',`cat_id`='2',`rank`='0',`status`='1' WHERE id=11<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />id:2<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:68class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='c1',`title_en`='c1',`content`='<p>
	<img alt="" src="http://localhost/pree/upload/5074f32d9ed0fMNDLogo.jpg" style="width: 125px; height: 125px; " /></p>',`keyword`='',`keyword_en`='',`url`='',`cat_id`='1',`rank`='0',`status`='1' WHERE id=2<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />id:3<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:68class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='c2',`title_en`='c2',`content`='<p>
	<img alt="" src="http://localhost/pree/upload/5074f3431c50bcfalogo.png" style="width: 360px; height: 60px; " /></p>',`keyword`='',`keyword_en`='',`url`='',`cat_id`='1',`rank`='0',`status`='1' WHERE id=3<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />id:4<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:68class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='c3',`title_en`='c3',`content`='<p>
	<img alt="" src="http://localhost/pree/upload/5074f35d0ec91Acupuncturist.jpg" style="width: 141px; height: 116px; " /></p>',`keyword`='',`keyword_en`='',`url`='',`cat_id`='2',`rank`='0',`status`='1' WHERE id=4<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />lob:aaaa<span style="color:red;">file:C:\wamp\www\pree\application\module\front\controller\common.phpline:38class:App\Module\Front\Controller\Commonmethod:App\Module\Front\Controller\Common::home</span><br /><br />lob:aaaa<span style="color:red;">file:C:\wamp\www\pree\application\module\front\controller\common.phpline:38class:App\Module\Front\Controller\Commonmethod:App\Module\Front\Controller\Common::home</span><br /><br />id:8<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:68class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='ccc',`title_en`='',`content`='',`keyword`='',`keyword_en`='',`url`='',`cat_id`='1',`rank`='0',`status`='1' WHERE id=8<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />id:8<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:68class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='ccc111',`title_en`='',`content`='<p>
	<img alt="" src="http://localhost/pree/upload/5074f46ab4d51nurse.jpg" style="width: 141px; height: 116px; " /></p>',`keyword`='',`keyword_en`='',`url`='',`cat_id`='1',`rank`='0',`status`='1' WHERE id=8<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />id:7<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:68class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='ccc3333',`title_en`='',`content`='<p>
	cccc<img alt="" src="http://localhost/pree/upload/5074f4814ecc6natura therapist.jpg" style="width: 141px; height: 116px; " /></p>',`keyword`='',`keyword_en`='',`url`='',`cat_id`='1',`rank`='0',`status`='1' WHERE id=7<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />lob:aaaa<span style="color:red;">file:C:\wamp\www\pree\application\module\front\controller\common.phpline:38class:App\Module\Front\Controller\Commonmethod:App\Module\Front\Controller\Common::home</span><br /><br />lob:aaaa<span style="color:red;">file:C:\wamp\www\pree\application\module\front\controller\common.phpline:38class:App\Module\Front\Controller\Commonmethod:App\Module\Front\Controller\Common::home</span><br /><br />id:2<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:68class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='c1',`title_en`='c1',`content`='',`keyword`='',`keyword_en`='',`url`='',`cat_id`='1',`rank`='0',`status`='1' WHERE id=2<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />lob:aaaa<span style="color:red;">file:C:\wamp\www\pree\application\module\front\controller\common.phpline:38class:App\Module\Front\Controller\Commonmethod:App\Module\Front\Controller\Common::home</span><br /><br />lob:aaaa<span style="color:red;">file:C:\wamp\www\pree\application\module\front\controller\common.phpline:38class:App\Module\Front\Controller\Commonmethod:App\Module\Front\Controller\Common::home</span><br /><br />lob:aaaa<span style="color:red;">file:C:\wamp\www\pree\application\module\front\controller\common.phpline:38class:App\Module\Front\Controller\Commonmethod:App\Module\Front\Controller\Common::home</span><br /><br />id:11<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:70class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='a1',`title_en`='a1',`content`='<p>
	<a href="http://localhost/pree/upload/5074f2a9187aecystic_fib_logo.png"><img alt="" src="http://localhost/pree/upload/5074f2e639a08cystic_fib_logo.png" style="width: 60px; height: 60px; " /></a></p>',`keyword`='',`keyword_en`='',`abstract`='aaaaaaaaa',`url`='',`cat_id`='2',`rank`='0',`status`='1' WHERE id=11<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />id:1<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:70class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='a1a11',`title_en`='',`content`='<h1>
	a1a1a11</h1>',`keyword`='',`keyword_en`='',`abstract`='bbbbbbbbbbbbbb',`url`='',`cat_id`='1',`rank`='0',`status`='1' WHERE id=1<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />id:5<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:70class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='aaa1',`title_en`='',`content`='<p>
	bbb1</p>',`keyword`='',`keyword_en`='',`abstract`='ccccccccccccccccccc',`url`='',`cat_id`='2',`rank`='0',`status`='1' WHERE id=5<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />id:6<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:70class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='ADFASFDS',`title_en`='',`content`='<p>
	ASDASDFSADF</p>',`keyword`='',`keyword_en`='',`abstract`='dddddddddddddddd',`url`='',`cat_id`='2',`rank`='0',`status`='1' WHERE id=6<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />id:2<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:70class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='c1',`title_en`='c1',`content`='',`keyword`='',`keyword_en`='',`abstract`='eeeeeeeeeeeeeee',`url`='',`cat_id`='1',`rank`='0',`status`='1' WHERE id=2<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />id:3<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:70class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='c2',`title_en`='c2',`content`='<p>
	<img alt="" src="http://localhost/pree/upload/5074f3431c50bcfalogo.png" style="width: 360px; height: 60px; " /></p>',`keyword`='',`keyword_en`='',`abstract`='fffffffffffffff',`url`='',`cat_id`='1',`rank`='0',`status`='1' WHERE id=3<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />id:4<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:70class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='c3',`title_en`='c3',`content`='<p>
	<img alt="" src="http://localhost/pree/upload/5074f35d0ec91Acupuncturist.jpg" style="width: 141px; height: 116px; " /></p>',`keyword`='',`keyword_en`='',`abstract`='ggggggggggggg',`url`='',`cat_id`='2',`rank`='0',`status`='1' WHERE id=4<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />id:8<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:70class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='ccc111',`title_en`='',`content`='<p>
	<img alt="" src="http://localhost/pree/upload/5074f46ab4d51nurse.jpg" style="width: 141px; height: 116px; " /></p>',`keyword`='',`keyword_en`='',`abstract`='gggggggggggggggg',`url`='',`cat_id`='1',`rank`='0',`status`='1' WHERE id=8<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />id:7<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:70class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='ccc3333',`title_en`='',`content`='<p>
	cccc<img alt="" src="http://localhost/pree/upload/5074f4814ecc6natura therapist.jpg" style="width: 141px; height: 116px; " /></p>',`keyword`='',`keyword_en`='',`abstract`='hhhhhhhhhhhhhhhhh',`url`='',`cat_id`='1',`rank`='0',`status`='1' WHERE id=7<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />id:9<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:70class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='d1',`title_en`='',`content`='<p>
	d1</p>',`keyword`='d1',`keyword_en`='d1',`abstract`='iiiiiiiiiiiii',`url`='d1',`cat_id`='2',`rank`='1',`status`='1' WHERE id=9<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />id:10<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\blog.phpline:70class:App\Module\Admin\Controller\Blogmethod:App\Module\Admin\Controller\Blog::update</span><br /><br />query:UPDATE blog SET `title`='d21',`title_en`='d21',`content`='<p>
	d21</p>',`keyword`='d21',`keyword_en`='d21',`abstract`='jjjjjjjjjjjj',`url`='d21',`cat_id`='4',`rank`='21',`status`='0' WHERE id=10<span style="color:red;">file:C:\wamp\www\pree\application\model\base\blog.phpline:85class:App\Model\Base\Blogmethod:App\Model\Base\Blog::update</span><br /><br />lob:aaaa<span style="color:red;">file:C:\wamp\www\pree\application\module\front\controller\common.phpline:38class:App\Module\Front\Controller\Commonmethod:App\Module\Front\Controller\Common::home</span><br /><br />id:1<span style="color:red;">file:C:\wamp\www\pree\application\module\admin\controller\article.phpline:70class:App\Module\Admin\Controller\Articlemethod:App\Module\Admin\Controller\Article::update</span><br /><br />id:1<span style="color:red;">file:F:\jian\wamp\www\pree\application\module\admin\controller\articlecategory.phpline:60class:App\Module\Admin\Controller\Articlecategorymethod:App\Module\Admin\Controller\Articlecategory::update</span><br /><br />arr:Array
(
    [title] => 澳洲保险常识
    [title_en] => Australia Insurance Knowledge
    [keyword] => 澳洲,保险,常识
    [keyword_en] => Australia Insurance Knowledge
    [url] => 
    [description] => <p>
	c111</p>
    [status] => 1
)
<span style="color:red;">file:F:\jian\wamp\www\pree\application\transaction\articlecategory.phpline:26class:App\Transaction\Articlecategorymethod:App\Transaction\Articlecategory::update_cat</span><br /><br />id:2<span style="color:red;">file:F:\jian\wamp\www\pree\application\module\admin\controller\articlecategory.phpline:60class:App\Module\Admin\Controller\Articlecategorymethod:App\Module\Admin\Controller\Articlecategory::update</span><br /><br />arr:Array
(
    [title] => 澳洲保险法规
    [title_en] => Australia Insurance Law
    [keyword] => 澳洲,保险,法规
    [keyword_en] => Australia Insurance Law
    [url] => 
    [description] => <p>
	b2b2</p>
    [status] => 1
)
<span style="color:red;">file:F:\jian\wamp\www\pree\application\transaction\articlecategory.phpline:26class:App\Transaction\Articlecategorymethod:App\Transaction\Articlecategory::update_cat</span><br /><br />id:3<span style="color:red;">file:F:\jian\wamp\www\pree\application\module\admin\controller\articlecategory.phpline:60class:App\Module\Admin\Controller\Articlecategorymethod:App\Module\Admin\Controller\Articlecategory::update</span><br /><br />arr:Array
(
    [title] => 澳洲保险教育
    [title_en] => Australia Insurance Education
    [keyword] => 澳洲,保险,教育
    [keyword_en] => Australia Insurance Education
    [url] => 
    [description] => <p>
	b3b3</p>
    [status] => 1
)
<span style="color:red;">file:F:\jian\wamp\www\pree\application\transaction\articlecategory.phpline:26class:App\Transaction\Articlecategorymethod:App\Transaction\Articlecategory::update_cat</span><br /><br />id:4<span style="color:red;">file:F:\jian\wamp\www\pree\application\module\admin\controller\articlecategory.phpline:60class:App\Module\Admin\Controller\Articlecategorymethod:App\Module\Admin\Controller\Articlecategory::update</span><br /><br />arr:Array
(
    [title] => 澳洲保险机构
    [title_en] => Australia Insurance Organization
    [keyword] => 澳洲,保险,机构
    [keyword_en] => Australia Insurance Organization
    [url] => 
    [description] => <p>
	b4b4</p>
    [status] => 1
)
<span style="color:red;">file:F:\jian\wamp\www\pree\application\transaction\articlecategory.phpline:26class:App\Transaction\Articlecategorymethod:App\Transaction\Articlecategory::update_cat</span><br /><br />